[build]
  base = "Frontend"   # Netlify ko Frontend folder ke andar le jane do
  command = "npm run build"   # Production build command
  publish = "dist"   # Corrected Path: dist folder directly deploy hoga

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
