[build]
  base = "Frontend"   # Yeh specify karega ki Netlify Frontend folder me jaye
  command = "npm run build"   # Production build command
  publish = "Frontend/dist"   # Vite ke output folder ko deploy kare

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
